export const DEFAULT_IGNORE_PATTERNS: string[] = [
  // Version control
  '.git',
  '.svn',
  '.hg',

  // Dependencies
  'node_modules',
  'vendor',
  '.venv',
  'venv',
  '__pycache__',
  'site-packages',

  // Build outputs
  'dist',
  'build',
  'out',
  '.next',
  '.nuxt',
  '.output',
  '.turbo',
  'coverage',
  '.nyc_output',

  // Environment & secrets
  '.env',
  '.env.*',
  '*.pem',
  '*.key',
  '*.cert',

  // Lock files
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'Pipfile.lock',
  'poetry.lock',
  'Gemfile.lock',
  'composer.lock',

  // Binary & media assets
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.webp',
  '*.svg',
  '*.ico',
  '*.mp4',
  '*.mp3',
  '*.wav',
  '*.pdf',
  '*.zip',
  '*.tar',
  '*.gz',
  '*.rar',
  '*.exe',
  '*.dll',
  '*.so',
  '*.dylib',
  '*.wasm',
  '*.ttf',
  '*.woff',
  '*.woff2',
  '*.eot',

  // IDE & OS artifacts
  '.DS_Store',
  'Thumbs.db',
  '.idea',
  '.vscode',
  '*.suo',
  '*.user',

  // Compiled assets
  '*.min.js',
  '*.min.css',
  '*.map',
  '*.chunk.js',

  // Generated / large data
  '*.log',
  '*.sqlite',
  '*.db',
  '*.csv',
  '*.parquet',

  // The output file itself
  'llm_context.md',
  '.contextslim.json',
];

export const LANGUAGE_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  mjs: 'javascript',
  cjs: 'javascript',
  py: 'python',
  rb: 'ruby',
  rs: 'rust',
  go: 'go',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  cs: 'csharp',
  cpp: 'cpp',
  c: 'c',
  h: 'c',
  hpp: 'cpp',
  php: 'php',
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  json: 'json',
  jsonc: 'jsonc',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  xml: 'xml',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'fish',
  ps1: 'powershell',
  md: 'markdown',
  mdx: 'mdx',
  sql: 'sql',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'protobuf',
  tf: 'hcl',
  hcl: 'hcl',
  dockerfile: 'dockerfile',
  vue: 'vue',
  svelte: 'svelte',
  astro: 'astro',
  r: 'r',
  lua: 'lua',
  ex: 'elixir',
  exs: 'elixir',
  hs: 'haskell',
  clj: 'clojure',
  dart: 'dart',
};
