import fs from 'fs/promises';
import path from 'path';
import type { FileEntry, SlimOptions } from './types.js';

interface WriteOutputParams {
  tree: string;
  files: FileEntry[];
  outputPath: string;
  options: SlimOptions;
}

export async function writeOutput({ tree, files, outputPath, options }: WriteOutputParams): Promise<void> {
  const sections: string[] = [header(options.targetDir)];

  if (options.tree && tree) {
    sections.push(treeSection(tree));
  }

  if (options.content && files.length > 0) {
    sections.push(filesSection(files));
  }

  const content = sections.join('\n\n');
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content, 'utf-8');
}

function header(targetDir: string): string {
  const now = new Date().toISOString();
  const projectName = path.basename(targetDir);
  return [
    `# LLM Context — ${projectName}`,
    '',
    `> Generated by [ContextSlim](https://github.com/your-org/contextslim) on ${now}`,
    `> This file is optimized for LLM consumption. Feed it directly to Claude, GPT, or any other LLM.`,
  ].join('\n');
}

function treeSection(tree: string): string {
  return [
    '## Project Structure',
    '',
    '```',
    tree,
    '```',
  ].join('\n');
}

function filesSection(files: FileEntry[]): string {
  const blocks = files.map((file) =>
    [
      `### \`${file.relativePath}\``,
      '',
      '```' + file.language,
      file.content,
      '```',
    ].join('\n')
  );

  return ['## File Contents', '', ...blocks].join('\n\n');
}
